name: Build and Run with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Upload exec
      uses: actions/upload-artifact@v3
      with:
        name: progGL
        path: bin/progGL
